CREATE USER GERACAO_ENERGIA IDENTIFIED BY senha;
-- GRANT CONNECT, RESOURCE TO GERACAO_ENERGIA;

-- Criação da tabela USINAS
CREATE TABLE GERACAO_ENERGIA.USINAS (
    USINA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    CAPACIDADE_GERACAO NUMBER(10,2),
    LOCALIZACAO VARCHAR2(100),
    CONSTRAINT PK_USINAS PRIMARY KEY (USINA_ID)
);

-- Criação da tabela MEDIDORES
CREATE TABLE GERACAO_ENERGIA.MEDIDORES (
    MEDIDOR_ID NUMBER NOT NULL,
    NUMERO_SERIE VARCHAR2(50),
    USINA_ID NUMBER,
    TIPO VARCHAR2(50),
    CONSTRAINT PK_MEDIDORES PRIMARY KEY (MEDIDOR_ID),
    CONSTRAINT FK_MEDIDORES_USINAS FOREIGN KEY (USINA_ID)
        REFERENCES USINAS (USINA_ID)
        ON DELETE CASCADE
);

-- Criação da tabela LEITURAS_ENERGIA
CREATE TABLE GERACAO_ENERGIA.LEITURAS_ENERGIA (
    LEITURA_ID NUMBER NOT NULL,
    MEDIDOR_ID NUMBER NOT NULL,
    DATA_LEITURA TIMESTAMP,
    CONSUMO NUMBER(10,2),
    CONSTRAINT PK_LEITURAS_ENERGIA PRIMARY KEY (LEITURA_ID),
    CONSTRAINT FK_LEITURAS_MEDIDORES FOREIGN KEY (MEDIDOR_ID)
        REFERENCES MEDIDORES (MEDIDOR_ID)
        ON DELETE CASCADE
);

-- Criação da tabela MANUTENCOES
CREATE TABLE GERACAO_ENERGIA.MANUTENCOES (
    MANUTENCAO_ID NUMBER NOT NULL,
    USINA_ID NUMBER NOT NULL,
    DATA_MANUTENCAO DATE,
    DESCRICAO CLOB,
    CUSTO NUMBER(10,2),
    CONSTRAINT PK_MANUTENCOES PRIMARY KEY (MANUTENCAO_ID),
    CONSTRAINT FK_MANUTENCOES_USINAS FOREIGN KEY (USINA_ID)
        REFERENCES USINAS (USINA_ID)
        ON DELETE CASCADE
);

-- Índices adicionais
CREATE UNIQUE INDEX IDX_USINAS_NOME ON GERACAO_ENERGIA.USINAS (NOME);
CREATE UNIQUE INDEX IDX_MEDIDORES_NUMERO_SERIE ON GERACAO_ENERGIA.MEDIDORES (NUMERO_SERIE);
